/**
 * Country names as they are written in data/community.csv, mapped to their
 * two-letter code. The little flag in front of a country is built from the
 * code, so no image files are needed. A country that is not listed simply
 * shows no flag — add it here and it appears.
 */
const CODES: Record<string, string> = {
  albania: "AL",
  argentina: "AR",
  armenia: "AM",
  australia: "AU",
  austria: "AT",
  azerbaijan: "AZ",
  belarus: "BY",
  belgium: "BE",
  brazil: "BR",
  bulgaria: "BG",
  canada: "CA",
  chile: "CL",
  china: "CN",
  colombia: "CO",
  croatia: "HR",
  cyprus: "CY",
  "czech republic": "CZ",
  czechia: "CZ",
  denmark: "DK",
  egypt: "EG",
  england: "GB",
  estonia: "EE",
  finland: "FI",
  france: "FR",
  georgia: "GE",
  germany: "DE",
  greece: "GR",
  hungary: "HU",
  iceland: "IS",
  india: "IN",
  iran: "IR",
  iraq: "IQ",
  ireland: "IE",
  israel: "IL",
  italy: "IT",
  japan: "JP",
  kazakhstan: "KZ",
  kenya: "KE",
  latvia: "LV",
  lebanon: "LB",
  lithuania: "LT",
  luxembourg: "LU",
  malta: "MT",
  mexico: "MX",
  moldova: "MD",
  morocco: "MA",
  "new zealand": "NZ",
  nigeria: "NG",
  "north macedonia": "MK",
  norway: "NO",
  poland: "PL",
  portugal: "PT",
  romania: "RO",
  russia: "RU",
  scotland: "GB",
  serbia: "RS",
  slovakia: "SK",
  slovenia: "SI",
  "south africa": "ZA",
  "south korea": "KR",
  korea: "KR",
  spain: "ES",
  sweden: "SE",
  switzerland: "CH",
  syria: "SY",
  "the netherlands": "NL",
  netherlands: "NL",
  turkey: "TR",
  türkiye: "TR",
  ukraine: "UA",
  "united kingdom": "GB",
  uk: "GB",
  "united states": "US",
  usa: "US",
  wales: "GB",
};

/** The flag for a country name, or null if we do not know the country. */
export function flagFor(country: string): string | null {
  const code = CODES[country.trim().toLowerCase()];
  if (!code) return null;
  // Regional indicator letters: A is U+1F1E6, and so on.
  return String.fromCodePoint(...[...code].map((letter) => 0x1f1e6 + letter.charCodeAt(0) - 65));
}
